### ISSUE TITLE
필수 PHP 모듈 소개하는데에서 php-mysql이 빠져있습니다.

### ISSUE THREAD

**Issue by pocketoy** [rhymix/rhymix-docs#10]
https://github.com/rhymix/rhymix-docs/blob/master/ko/introduction/requirements.md

필수 PHP 모듈 소개하는데에서 php-mysql이 빠져있습니다.

**Comment by pocketoy** [comment]
그럼 문서에 그렇게 명시해야 하지 않을까요? 
[PDO 및 PDO의 MySQL 드라이버 패키지(php-mysql 또는 운영체제에 따라 다른 이름)] 이라는 식으로 말입니다.

**Comment by kijin** [comment]
PDO_MySQL을 명시하도록 수정했습니다.^^
