### ISSUE TITLE
블랙리스트 관련 설명 필요

### ISSUE THREAD

**Issue by YJSoft** [rhymix/rhymix-docs#11]
라이믹스에는 블랙리스트라 불리는 목록이 있습니다. 라이믹스와 호환되지 않으면서 동시에 라이믹스 내장 기능의 동작을 방해하는 자료가 등록됩니다.

즉 라이믹스의 기능과 중복되거나 동작하지 않는다고 추가되지는 않는다는 점인데요, 이 점은 어디에도 안내되고 있지 않습니다. 이 때문에 라이믹스 블랙리스트 추가 요청 중 실제 블랙리스트에 추가될 필요가 없는 자료의 추가 요청이 종종 발생합니다. 어떤 자료가 추가되는 것인지 등 기준을 명확히 정하고 문서화하면 좋을것 같습니다.

**Comment by kijin** [comment]
코어의 블랙리스트가 뭔가 대단한 것인 줄 생각하는 분들이 있는 모양인데, 그냥 라이믹스 초창기에 다수의 서드파티 자료를 코어에 흡수하면서 충돌 방지를 위해 도입한 코어 내부의 필터일 뿐 대외적으로 신경쓸 만한 것이 전혀 아닙니다.

사실상 블랙리스트 기능 자체가 일종의 레거시 코드입니다. 보안 문제를 유발하는 트랙백 모듈 외에는 지난 3년 가까이 블랙리스트에 추가된 것이 없고, 앞으로도 거의 변경되지 않을 것으로 예상합니다. 특정한 자료와 관련된 호환성 문제 보고 또는 조사 요청을 선행하지 않고 직접적으로 블랙리스트 추가/삭제/수정을 요청하는 이슈는 **원칙적으로 모두 기각하겠습니다.**

상술했듯 코어 내부의 필터일 뿐 공식적인 API가 아니고, 사용을 권장하는 것도 아니며, 다른 유용한 서드파티 자료의 이용에 지장을 주는 것도 아니므로 매뉴얼에서 특별히 다룰 가치도 없다고 생각합니다. XE나 구 버전에서 업그레이드할 때 큰 문제를 일으킬 수 있는 모듈이라든지, 과거 코어의 일부였으나 더이상 배포하지 않는 애드온 등의 목록은 [서드파티 자료 호환성 체크리스트](https://rhymix.org/manual/introduction/thirdparty-checklist)에서 관리하고 있으니, 필요시 추가나 수정을 환영합니다.
