### ISSUE TITLE
Rhymix requires MySQL 5.0.7 or later. Current MySQL version is 에러 메시지

### ISSUE THREAD

**Issue by sisepyo** [rhymix/rhymix-docs#3]
호스팅사 : CAFE 24
PHP버전 : 7.0
MySQL : MariaDB 10.0.x

XE -> 라이믹스로 업그레이드를 하기 위해 FTP로 라이믹스 파일을 덮어씌웠습니다.
Rhymix requires MySQL 5.0.7 or later. Current MySQL version is 에러 메시지가 뜹니다.

**Comment by kijin** [comment]
제가 몇 년 전부터 카페24 PHP 7.0 계정에서 라이믹스를 테스트로 돌리고 있습니다만, 말씀하신 것과 같은 증상은 보지 못했습니다. 그러나 카페24 같은 대형 호스팅 업체는 동일한 상품을 신청하더라도 서버마다 세팅이 조금씩 다른 경우가 있습니다. 특정 서버에서만 버전이 이상하게 나오는 것이 아닐까 합니다.

classes/db/DBMysql.class.php 80줄 전후에

    var_dump($mysqli->server_info);

코드를 추가하여 화면에 뭐라고 찍히는지 확인해 주시기 바랍니다.

예를 들면 아래와 같이 나올 것입니다.

    string(21) "5.5.5-10.1.13-MariaDB"

**Comment by kijin** [comment]
라이믹스 코어에서 해당부분 체크가 제거되었으므로 이 이슈는 닫습니다.
